#!/bin/sh
set -u

SD_CONFIG=/etc/fw_env.sd.config
FLASH_CONFIG=/run/fw_env.flash.config

BACKEND=""
CONFIG=""
BOOT_MOUNTED_BY_US=0
ENV_DIRTY=0

die()
{
    echo "fwenv: $*" >&2
    exit 1
}

find_tool()
{
    NAME="$1"

    for TOOL in "/usr/sbin/$NAME" "/usr/bin/$NAME"; do
        [ -x "$TOOL" ] && {
            printf '%s\n' "$TOOL"
            return 0
        }
    done

    TOOL="$(command -v "$NAME" 2>/dev/null || true)"
    [ -n "$TOOL" ] || die "missing $NAME"
    printf '%s\n' "$TOOL"
}

cleanup()
{
    STATUS=$?

    if [ "$BOOT_MOUNTED_BY_US" -eq 1 ]; then
        if [ "$ENV_DIRTY" -eq 1 ]; then
            # Make the FAT-backed environment durable before removing /boot.
            sync
        fi

        umount /boot || {
            echo "fwenv: warning: unable to unmount /boot" >&2
            [ "$STATUS" -ne 0 ] || STATUS=1
        }
        BOOT_MOUNTED_BY_US=0
    fi

    trap - EXIT INT TERM
    exit "$STATUS"
}

find_flash_env_mtd()
{
    [ -r /proc/mtd ] || return 1

    while read -r DEV SIZE ERASE NAME REST; do
        [ "$NAME" = '"uboot-env"' ] || continue

        # The ratified NOR map gives this partition exactly two 64 KiB
        # erase sectors. A geometry mismatch is a hard refusal, not "missing".
        if [ "$SIZE" != "00020000" ]; then
            echo "fwenv: uboot-env MTD partition has unexpected size 0x$SIZE" >&2
            return 2
        fi
        case "$ERASE" in
            00001000|00010000)
                # MX25V1635F supports both 4 KiB subsectors and 64 KiB blocks.
                # Linux normally prefers 4 KiB erase units; U-Boot deliberately
                # reserves each redundant copy on a 64 KiB boundary.
                ;;
            *)
                echo "fwenv: uboot-env MTD partition has unexpected erase size 0x$ERASE" >&2
                return 2
                ;;
        esac

        DEV="${DEV%:}"
        if [ ! -c "/dev/$DEV" ]; then
            echo "fwenv: MTD partition $DEV exists in /proc/mtd but /dev/$DEV is missing" >&2
            return 2
        fi

        printf '%s %s\n' "/dev/$DEV" "$ERASE"
        return 0
    done < /proc/mtd

    return 1
}

prepare_flash_config()
{
    MTD_INFO="$(find_flash_env_mtd)"
    MTD_STATUS=$?

    case "$MTD_STATUS" in
        0) ;;
        1)
            # The production kernel may intentionally leave SPI-NOR as an
            # on-demand module. A blacklist only blocks automatic loading;
            # explicit modprobe here preserves fast boot and enables env access.
            if command -v modprobe >/dev/null 2>&1; then
                modprobe spi-nor >/dev/null 2>&1 || true
            fi
            MTD_INFO="$(find_flash_env_mtd)"
            MTD_STATUS=$?
            ;;
        *)
            die "refusing invalid uboot-env MTD geometry"
            ;;
    esac

    [ "$MTD_STATUS" -eq 0 ] && [ -n "$MTD_INFO" ] ||
        die "cannot find validated MTD partition labelled uboot-env"

    set -- $MTD_INFO
    MTD_DEV="$1"
    MTD_ERASE="$2"

    mkdir -p /run || die "cannot create /run for flash environment config"

    {
        echo '# Generated by NextGen fwenv.sh from the uboot-env MTD label.'
        echo '# device offset env-size erase-size'
        printf '%s\t0x00000\t0x4000\t0x%s\n' "$MTD_DEV" "$MTD_ERASE"
        printf '%s\t0x10000\t0x4000\t0x%s\n' "$MTD_DEV" "$MTD_ERASE"
    } > "$FLASH_CONFIG" ||
        die "cannot create flash environment config"

    chmod 0600 "$FLASH_CONFIG" ||
        die "cannot protect flash environment config"
}

select_config()
{
    CMDLINE="$(cat /proc/cmdline 2>/dev/null || true)"

    case " $CMDLINE " in
        *" nextgen.env=sd "*)
            BACKEND=sd
            ;;
        *" nextgen.env=nor "*|*" nextgen.env=flash "*)
            BACKEND=flash
            ;;
    esac

    if [ -z "$BACKEND" ]; then
        # Compatibility only for the existing SD image, which predates the
        # explicit nextgen.env= marker. A flash boot must provide the marker;
        # do not guess a writable NOR target from MTD numbering.
        case " $CMDLINE " in
            *" root=/dev/mmcblk"*)
                BACKEND=sd
                ;;
            *)
                die "boot environment backend is not identified"
                ;;
        esac
    fi

    case "$BACKEND" in
        sd)
            [ -r "$SD_CONFIG" ] ||
                die "missing SD environment config: $SD_CONFIG"

            if ! grep -qs ' /boot ' /proc/mounts; then
                mount /boot ||
                    die "unable to mount /boot for SD U-Boot environment"
                BOOT_MOUNTED_BY_US=1
            fi
            CONFIG="$SD_CONFIG"
            ;;
        flash)
            # Resolve by the DT partition label on every invocation rather
            # than assuming an MTD number. The generated config describes the
            # two redundant 16 KiB env images in independent 64 KiB sectors.
            prepare_flash_config
            [ -r "$FLASH_CONFIG" ] ||
                die "flash environment config was not generated"
            CONFIG="$FLASH_CONFIG"
            ;;
        *)
            die "unsupported backend: $BACKEND"
            ;;
    esac
}

set_if_changed()
{
    NAME="$1"
    VALUE="$2"

    LINE="$("$FW_PRINTENV" -c "$CONFIG" "$NAME" 2>/dev/null || true)"
    case "$LINE" in
        "$NAME=$VALUE")
            return 0
            ;;
    esac

    echo "fwenv: set $NAME=$VALUE" >&2
    ENV_DIRTY=1
    "$FW_SETENV" -c "$CONFIG" "$NAME" "$VALUE"
}

[ "$#" -ge 1 ] || die "usage: $0 {print|set|set-many|config} [arguments...]"
ACTION="$1"
shift

trap cleanup EXIT INT TERM
select_config

case "$ACTION" in
    config)
        [ "$#" -eq 0 ] || die "config takes no arguments"
        printf '%s\n' "$CONFIG"
        ;;
    print)
        FW_PRINTENV="$(find_tool fw_printenv)"
        "$FW_PRINTENV" -c "$CONFIG" "$@"
        ;;
    set)
        [ "$#" -ge 1 ] || die "set requires a variable name"
        FW_SETENV="$(find_tool fw_setenv)"
        ENV_DIRTY=1
        "$FW_SETENV" -c "$CONFIG" "$@"
        ;;
    set-many)
        [ "$#" -ge 2 ] || die "set-many requires name/value pairs"
        [ $(( $# % 2 )) -eq 0 ] || die "set-many requires name/value pairs"

        FW_PRINTENV="$(find_tool fw_printenv)"
        FW_SETENV="$(find_tool fw_setenv)"

        while [ "$#" -gt 0 ]; do
            NAME="$1"
            VALUE="$2"
            shift 2
            set_if_changed "$NAME" "$VALUE" || exit $?
        done
        ;;
    *)
        die "unknown action: $ACTION"
        ;;
esac
