#!/bin/sh

case "${1:-}" in
    start)
        echo "Starting NextGen bring-up provisioning"
        /opt/nextgen/platform/bin/nextgen-bringup.sh
        ;;
    stop)
        ;;
    restart)
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
